Application:
  Window:
    Properties:
      _Name: PsyTron
      _Width: 1280   # 640 1280 1920
      _Height: 960  # 480 960 1080
      _Bits: 16
      _FPS: 60
      _Fullscreen: false
      _BulletSpeedFactor: '1.0' # use 0.5 for Resolutions under 1280 * 960
      _DebugMode: false
      _SkipIntro: false
  Resources:
    Language: Spanish
    DialogFile: Data/intro.yml
    Material:
     _name: Test
     _effect: Simple
     _technique: Technique0
    Scene:
     - _name: Dragon
       _file: ./Src/Data/Scene/dragonsmall.DAE
       _info: staticModel
     - _name: LoadFailed
       _file: ./Src/Data/Scene/fail.DAE
       _info: staticModel
     - _name: Ring
       _file: ./Src/Data/Scene/RingO.dae
       _info: staticModel
    Font:
      _name: Font1
      _file: ./Src/Data/Fonts/Test1.fnt
      _info: Font
